### ISSUE TITLE
Getting error sudo python setup.py clean

### ISSUE THREAD

**Issue by jangjichang** [InFoCusp/tf_cnnvis#38]
Hi I'm jang

Thank you for sharing your work.

My PC enviornment is Ubuntu 16.04 LTS and I downloads tf_cnnvis on /home/jc using git.

I entered the following command :

1.
pip install tensorflow numpy scipy h5py wget Pillow six scikit-image

2.
git clone https://github.com/InFoCusp/tf_cnnvis.git

3.
sudo pip install setuptools
`[sudo] password for jc: 
The directory '/home/jc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: setuptools in /home/jc/.local/lib/python2.7/site-packages
`
4.
sudo pip install six
`The directory '/home/jc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement `

5.
jc@jc-15N540-UT50K:~/tf_cnnvis$ sudo python setup.py install
```
running install
running bdist_egg
running egg_info
writing requirements to tf_cnnvis.egg-info/requires.txt
writing tf_cnnvis.egg-info/PKG-INFO
writing top-level names to tf_cnnvis.egg-info/top_level.txt
writing dependency_links to tf_cnnvis.egg-info/dependency_links.txt
reading manifest file 'tf_cnnvis.egg-info/SOURCES.txt'
writing manifest file 'tf_cnnvis.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/tf_cnnvis
copying build/lib.linux-x86_64-2.7/tf_cnnvis/utils.py -> build/bdist.linux-x86_64/egg/tf_cnnvis
copying build/lib.linux-x86_64-2.7/tf_cnnvis/__init__.py -> build/bdist.linux-x86_64/egg/tf_cnnvis
copying build/lib.linux-x86_64-2.7/tf_cnnvis/tf_cnnvis.py -> build/bdist.linux-x86_64/egg/tf_cnnvis
byte-compiling build/bdist.linux-x86_64/egg/tf_cnnvis/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/tf_cnnvis/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/tf_cnnvis/tf_cnnvis.py to tf_cnnvis.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying tf_cnnvis.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tf_cnnvis.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tf_cnnvis.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tf_cnnvis.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying tf_cnnvis.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/tf_cnnvis-1.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing tf_cnnvis-1.0.0-py2.7.egg
Removing /usr/local/lib/python2.7/dist-packages/tf_cnnvis-1.0.0-py2.7.egg
Copying tf_cnnvis-1.0.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
tf-cnnvis 1.0.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/tf_cnnvis-1.0.0-py2.7.egg
Processing dependencies for tf-cnnvis==1.0.0
Searching for scikit-image==0.13.1
Best match: scikit-image 0.13.1
Adding scikit-image 0.13.1 to easy-install.pth file
Installing skivi script to /usr/local/bin

Using /home/jc/.local/lib/python2.7/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for Pillow==5.0.0
Best match: Pillow 5.0.0
Adding Pillow 5.0.0 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for wget==3.2
Best match: wget 3.2
Adding wget 3.2 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for h5py==2.7.1
Best match: h5py 2.7.1
Adding h5py 2.7.1 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for scipy==1.0.0
Best match: scipy 1.0.0
Adding scipy 1.0.0 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for numpy==1.14.1
Best match: numpy 1.14.1
Adding numpy 1.14.1 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for matplotlib==2.1.2
Best match: matplotlib 2.1.2
Adding matplotlib 2.1.2 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for networkx==2.1
Best match: networkx 2.1
Adding networkx 2.1 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for PyWavelets==0.5.2
Best match: PyWavelets 0.5.2
Adding PyWavelets 0.5.2 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for pytz==2018.3
Best match: pytz 2018.3
Adding pytz 2018.3 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for subprocess32==3.2.7
Best match: subprocess32 3.2.7
Adding subprocess32 3.2.7 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for backports.functools-lru-cache==1.5
Best match: backports.functools-lru-cache 1.5
Adding backports.functools-lru-cache 1.5 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for pyparsing==2.2.0
Best match: pyparsing 2.2.0
Adding pyparsing 2.2.0 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Searching for decorator==4.2.1
Best match: decorator 4.2.1
Adding decorator 4.2.1 to easy-install.pth file

Using /home/jc/.local/lib/python2.7/site-packages
Finished processing dependencies for tf-cnnvis==1.0.0
/home/jc/.local/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

6.
jc@jc-15N540-UT50K:~/tf_cnnvis$ sudo python setup.py clean
```
running clean
Traceback (most recent call last):
  File "setup.py", line 67, in <module>
    'clean': CleanCommand,
  File "/home/jc/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
```

I get error like that. could you explain more detail how to use this code?

thank you

**Comment by falaktheoptimist** [comment]
Hi @jangjichang 
Thanks for taking the time to point out this bug. We've fixed this in the latest commit. Clean should work too now. Please check
Thanks!
